workflows:
  ios-free-account:
    name: iOS Free Account Workflow
    max_build_duration: 60
    environment:
      vars:
        APPLE_ID: $APPLE_ID               # your Apple ID email
        APP_SPECIFIC_PASSWORD: $APP_SPECIFIC_PASSWORD  # generated app-specific password
      xcode: latest
    triggering:
      events:
        - push
    scripts:
      - name: Build iOS app
        script: |
          set -e
          xcodebuild clean archive \
            -project Practice1.xcodeproj \
            -scheme Practice1 \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath $CM_BUILD_DIR/Practice1.xcarchive \
            -allowProvisioningUpdates

      - name: Export IPA
        script: |
          set -e
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/Practice1.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $CM_BUILD_DIR/ipa
    artifacts:
      - $CM_BUILD_DIR/ipa/Practice1.ipa
