workflows:
  ios-free-account:
    name: iOS Free Account Workflow
    max_build_duration: 60
    environment:
      vars:
        APPLE_ID: $APPLE_ID          # your Apple ID email, e.g., nchalygu@verizon.net
        APP_SPECIFIC_PASSWORD: $APP_SPECIFIC_PASSWORD  # generated app-specific password
      flutter: false
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - manual
    scripts:
      - name: Install dependencies
        script: |
          set -e
          pod install --project-directory=.
      - name: Build iOS app
        script: |
          set -e
          xcodebuild clean archive \
            -workspace Practice1.xcworkspace \
            -scheme Practice1 \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath $CM_BUILD_DIR/Practice1.xcarchive \
            DEVELOPMENT_TEAM=<YOUR_TEAM_ID> \
            CODE_SIGN_IDENTITY="iPhone Developer"
      - name: Export IPA
        script: |
          set -e
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/Practice1.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $CM_BUILD_DIR/ipa
    artifacts:
      - $CM_BUILD_DIR/ipa/Practice1.ipa
